### ISSUE TITLE
Uno.Check 1.15.0.0 Check Fail

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno.check#182]
Hi @jeromelaban,

After migrating Visual Studio from version 17.7.4 to version 17.7.5 we have executed the Uno.Check tool.

The tool has recommended us to update it to version 1.15.0.0.

After this, it has updated some components but the one seen in the screenshot fails:

![image](https://github.com/unoplatform/uno.check/assets/3469909/c0514aba-491d-4ad4-b282-a725bb016115)

Continue...

![image](https://github.com/unoplatform/uno.check/assets/3469909/7dde262a-eb68-4421-8aff-5dd0f32fbbf2)

Thanks!

**Comment by jeromelaban** [comment]
Thanks for the report, this is an issue coming from Microsoft: https://github.com/dotnet/aspnetcore/issues/51273. It may be a transitive issue that could be fixed in the next days.

**Comment by Suriman** [comment]
Thanks!

**Comment by Suriman** [comment]
Hi @jeromelaban, Microsoft has closed the issue you mention. I have updated the version of uno.check to 1.16.0 and the problem persists. Do I have to do anything special?

**Comment by jeromelaban** [comment]
Thanks for the update. We do not have control over this part of .NET, and if package signing does not work on your end it may be a  local issue. You can try repairing visual studio and see if it helps.

**Comment by Suriman** [comment]
Hi @jeromelaban, I have repaired Visual Studio and it still doesn't work. It baffles me a little that the Microsoft issue is closed but the problem persists.

**Comment by jeromelaban** [comment]
Thanks for the update. Does it happen on other machines as well?

**Comment by Suriman** [comment]
Hi @jeromelaban. Yes, it happens on other machines. Additionally, I have updated to version 1.16.0 of Uno.Check and I have reinstalled VS 2022 17.7.5. The problem persists on all machines. Any ideas how can I fix it?

**Comment by jeromelaban** [comment]
Upon additional validation, it seems that this issue is related to Windows itself, where this package (among others): https://www.nuget.org/packages/Microsoft.NET.Sdk.macOS.Manifest-7.0.100

fails to validate on some versions of windows, which can be validated with this command (reference [from the SDK](https://github.com/dotnet/sdk/blob/61867967918ee4bd6519e1ae4bbc7dfefbc38ce4/src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs#L79)):

```
dotnet nuget verify --all "C:\Users\jerome.uno\Downloads\microsoft.net.sdk.macos.manifest-7.0.100.13.3.7107.nupkg" & echo %errorlevel%
```

Some windows machines will return 0, some will return 1, all while returning the same output, with all running on 7.0.401.

The originally referenced issue is likely not the one we're chasing here, and it is technically unrelated to uno-check. It may be an issue with the certificates store from windows, or maybe with `dotnet nuget verify` itself. NPE on windows does not report any error either on machines where `dotnet nuget verify` fails.

A temporary workaround may be to add the ability for uno.check to skip signatures, using [the hidden parameter `--skip-sign-check`](https://github.com/dotnet/sdk/blob/d93faa75c98482a2103a13a52b73bc3e6d3b8dc7/src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommandParser.cs#L23-L24), until we can find a stable workaround or fix, though it is a security risk and it will need to not be advertised as well.

**Comment by jeromelaban** [comment]
dotnet/sdk issue: https://github.com/dotnet/sdk/issues/36270

**Comment by Suriman** [comment]
Hi @jeromelaban, the `--skip-sign-check `parameter, I understand that it cannot currently be used because I have tried to use it with version 1.16.0 of Uno.Check and the same error occurs. Could you add this functionality to the Uno.Check tool temporarily?

**Comment by jeromelaban** [comment]
Yes, the parameter is not available in uno-check at this time, though it seems that .NET 7.0.402 is fixing this particular overall issue. A new build of uno.check is being produced, you'll be able to validate if it helps on your end.

**Comment by jeromelaban** [comment]
Updating to Uno 1.16.1 fixes the issue, it is being deployed to nuget as of this writing.

@Suriman Thanks for your help!
