### ISSUE TITLE
uno.check do not find my dotnet install on linux

### ISSUE THREAD

**Issue by junelac** [unoplatform/uno.check#317]
Hello,

I installed dotnet with the mise utility. It works:
```
 dotnet --version
9.0.101
```

And with it, I installed uno-check. However when I run it I get this error:

```
~/.dotnet/tools/uno-check                                                 ─╯

You must install .NET to run this application.

App: /net/moana/user/menut/.dotnet/tools/uno-check
Architecture: x64
App host version: 6.0.25
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=opensuse-leap.15.5-x64&apphost_version=6.0.25
```

I suspect it is because dotnet is not installed in a standard location, but I would expect it to find it.

**Comment by jeromelaban** [comment]
Thanks for the report.

We've seen reports like those in the past though we were not able to reproduce. This particular error is caused by .NET itself. I wonder, if you do run something like:

```
dotnet install -g dotnet-serve
```
Then run:
```
~/.dotnet/tools/dotnet-serve
```

Does it work?

**Comment by junelac** [comment]
After looking around, setting DOTNET_ROOT (`export DOTNET_ROOT=<PATH_TO_DOTNET_DIR>`) solved the issue

**Comment by jeromelaban** [comment]
Thanks for the update! Indeed I did mean `dotnet tool install`.

**Comment by Pakti** [comment]
I'm experiencing the same issue. I can't determine whether `uno.check` fails to detect any .NET installation or whether it explicitly requires .NET 6. I have .NET 10 on a Linux distribution based on Ubuntu 22.04.:

```
$ dotnet --list-sdks
10.0.101 [/usr/lib/dotnet/sdk]
```

However, it seems that `~/.dotnet/tools/dotnet-serve` can't find the .NET location:

```
$ ~/.dotnet/tools/dotnet-serve
You must install .NET to run this application.

App: /home/pakti/.dotnet/tools/dotnet-serve
Architecture: x64
App host version: 10.0.1
.NET location: Not found

The following locations were searched:
  Application directory:
    /home/pakti/.dotnet/tools/.store/dotnet-serve/1.10.193/dotnet-serve/1.10.193/tools/net8.0/any/
  Environment variable:
    DOTNET_ROOT = /usr/share/dotnet

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&os=linuxmint.21.1&apphost_version=10.0.1
```

I would have tried again after installing the .NET 6.0.428 package still available from Microsoft’s repository, but it conflicts with the installed .NET 10.  It seems to be a known issue, and I might be able to rely on a user-local .NET installation. However, since .NET 6 has been out of support for over a year, I wonder whether `uno.check` will be upgraded to a more recent .NET version, or whether I could rebuild it myself against one.

Thanks for your assistance.
